server:
  port: 80
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  application:
    name: java-site
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=1h
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:site.db
  task:
    scheduling:
      pool:
        size: 5

mybatis:
  type-aliases-package: com.site.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

proxy:
  allowed-domains:
    - sci.ncut.edu.cn
  cache-enabled: true
  static-extensions:
    # 图片格式
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .bmp
    - .webp
    - .ico
    - .svg
    - .tiff
    - .raw
    # 字体文件
    - .woff
    - .woff2
    - .ttf
    - .eot
    - .otf
    
    # 媒体文件
    - .mp4
    - .mp3
    - .avi
    - .wmv
    - .flv
    - .mov
    - .wav
    
    # 文档文件
    - .pdf
    - .doc
    - .docx
    - .xls
    - .xlsx
    - .ppt
    - .pptx
    
    # 压缩文件
    - .zip
    - .rar
    - .7z
    - .tar
    - .gz
  forward-headers:
    - User-Agent
    - Accept
    - Accept-Language
    - Accept-Encoding

logging:
  level:
    com.site.mapper: DEBUG
    com.site: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 

admin:
  path: HSuu22299dhs