server:
  port: 9090
  tomcat:
    max-threads: 200
    min-spare-threads: 10
    max-connections: 10000
    connection-timeout: 20000
    accept-count: 100
    max-http-form-post-size: 4MB
    max-swallow-size: 4MB
    uri-encoding: UTF-8
    remote-ip-header: X-Forwarded-For
    protocol-header: X-Forwarded-Proto
    protocol-header-https-value: https

spring:
  application:
    name: java-site
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=1h
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:./data/site.db
  task:
    scheduling:
      pool:
        size: 5
  servlet:
    encoding:
      charset: UTF-8
      force: true
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  type-aliases-package: com.site.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    cache-enabled: true
    call-setters-on-nulls: true
    jdbc-type-for-null: NULL

proxy:
  allowed-domains:
    - sci.ncut.edu.cn
  cache-enabled: true
  static-extensions:
    # 图片格式
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .bmp
    - .webp
    - .ico
    - .svg
    - .tiff
    - .raw
    # 字体文件
    - .woff
    - .woff2
    - .ttf
    - .eot
    - .otf
    
    # 媒体文件
    - .mp4
    - .mp3
    - .avi
    - .wmv
    - .flv
    - .mov
    - .wav
    
    # 文档文件
    - .pdf
    - .doc
    - .docx
    - .xls
    - .xlsx
    - .ppt
    - .pptx
    
    # 压缩文件
    - .zip
    - .rar
    - .7z
    - .tar
    - .gz
  forward-headers:
    - User-Agent
    - Accept
    - Accept-Language
    - Accept-Encoding

logging:
  level:
    com.site.mapper: DEBUG
    com.site: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 

admin:
  path: HSuu22299dhs

app:
  base-dir: ${user.dir}