server:
  port: 9099
  address: 0.0.0.0
  tomcat:
    max-threads: 800
    min-spare-threads: 50
    max-connections: 20000
    connection-timeout: 30000
    accept-count: 1000
    max-http-form-post-size: 20MB
    max-swallow-size: 20MB
    uri-encoding: UTF-8
    remote-ip-header: X-Forwarded-For
    protocol-header: X-Forwarded-Proto
cert:
  service:
    url: http://127.0.0.1:8000  # Python证书服务的地址

spring:
  application:
    name: java-site
  main:
    allow-circular-references: true
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=10000,expireAfterWrite=1h
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:./data/site.db
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
  task:
    scheduling:
      pool:
        size: 10
  servlet:
    encoding:
      charset: UTF-8
      force: true
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      location: ./temp
      file-size-threshold: 10MB

mybatis:
  type-aliases-package: com.site.entity
  configuration:
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    cache-enabled: true
    call-setters-on-nulls: true
    jdbc-type-for-null: NULL

proxy:
  cache-enabled: true
  static-extensions:
    # 图片格式
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .bmp
    - .webp
    - .ico
    - .svg
    - .tiff
    - .raw
    # 字体文件
    - .woff
    - .woff2
    - .ttf
    - .eot
    - .otf
    
    # 媒体文件
    - .mp4
    - .mp3
    - .avi
    - .wmv
    - .flv
    - .mov
    - .wav
    
    # 文档文件
    - .pdf
    - .doc
    - .docx
    - .xls
    - .xlsx
    - .ppt
    - .pptx
    
    # 压缩文件
    - .zip
    - .rar
    - .7z
    - .tar
    - .gz
  forward-headers:
    - User-Agent
    - Accept
    - Accept-Language
    - Accept-Encoding
admin:
  path: HSuu22299dhs

app:
  base-dir: ${user.dir}

logging:
  level:
    root: INFO
    com.site: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"