    private String generateNginxConfig(String domain) {
        StringBuilder config = new StringBuilder();
        config.append("server {\n")
             .append("    listen 80;\n")
             .append(String.format("    server_name %s;\n", domain))
             .append("    return 301 https://$host$request_uri;\n")
             .append("}\n\n")
             .append("server {\n")
             .append("    listen 443 ssl http2;\n")
             .append(String.format("    server_name %s;\n\n", domain))
             .append("    # SSL证书配置\n")
             .append(String.format("    ssl_certificate %s/%s/fullchain.pem;\n", certPath, domain))
             .append(String.format("    ssl_certificate_key %s/%s/privkey.pem;\n", certPath, domain))
             .append("\n")
             .append("    # SSL配置优化\n")
             .append("    ssl_session_timeout 1d;\n")
             .append("    ssl_session_cache shared:SSL:50m;\n")
             .append("    ssl_session_tickets off;\n")
             .append("    ssl_protocols TLSv1.2 TLSv1.3;\n")
             .append("    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;\n")
             .append("    ssl_prefer_server_ciphers off;\n\n")
             .append("    # OCSP Stapling\n")
             .append("    ssl_stapling on;\n")
             .append("    ssl_stapling_verify on;\n")
             .append("    resolver 8.8.8.8 8.8.4.4 valid=300s;\n")
             .append("    resolver_timeout 5s;\n\n")
             .append("    # 安全相关头部\n")
             .append("    add_header Strict-Transport-Security \"max-age=31536000; includeSubDomains\" always;\n")
             .append("    add_header X-Frame-Options SAMEORIGIN;\n")
             .append("    add_header X-Content-Type-Options nosniff;\n")
             .append("    add_header X-XSS-Protection \"1; mode=block\";\n\n")
             .append("    # 反向代理到Java应用\n")
             .append("    location / {\n")
             .append("        proxy_pass http://localhost:9090;\n")
             .append("        proxy_set_header Host $host;\n")
             .append("        proxy_set_header X-Real-IP $remote_addr;\n")
             .append("        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n")
             .append("        proxy_set_header X-Forwarded-Proto $scheme;\n\n")
             .append("        # WebSocket支持\n")
             .append("        proxy_http_version 1.1;\n")
             .append("        proxy_set_header Upgrade $http_upgrade;\n")
             .append("        proxy_set_header Connection \"upgrade\";\n\n")
             .append("        # 超时设置\n")
             .append("        proxy_connect_timeout 60s;\n")
             .append("        proxy_send_timeout 60s;\n")
             .append("        proxy_read_timeout 60s;\n")
             .append("    }\n\n")
             .append("    # 静态文件缓存\n")
             .append("    location ~* \\.(jpg|jpeg|png|gif|ico|css|js)$ {\n")
             .append("        proxy_pass http://localhost:9090;\n")
             .append("        proxy_set_header Host $host;\n")
             .append("        expires 30d;\n")
             .append("        add_header Cache-Control \"public, no-transform\";\n")
             .append("    }\n")
             .append("}\n");
        
        return config.toString();
    }
