server:
  port: 443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: your_password
    key-store-type: PKCS12
    key-alias: tomcat
  http:
    port: 80
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  application:
    name: java-site
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=1h
  datasource:
    url: jdbc:h2:file:./sitedb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

proxy:
  allowed-domains:
    - sci.ncut.edu.cn
    - wf.ncut.edu.cn
  cache-enabled: true
  static-extensions:
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .bmp
    - .webp
    - .ico
    - .woff
    - .woff2
    - .ttf
    - .eot
    - .svg
  forward-headers:
    - User-Agent
    - Accept
    - Accept-Language
    - Accept-Encoding
    - Cookie

logging:
  level:
    com.site: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 