server:
  port: 801
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  application:
    name: java-site
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=1h
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:site.db

mybatis:
  type-aliases-package: com.site.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

proxy:
  allowed-domains:
    - sci.ncut.edu.cn
  cache-enabled: true
  static-extensions:
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .ico
  forward-headers:
    - User-Agent
    - Accept
    - Accept-Language
    - Accept-Encoding

logging:
  level:
    com.site.mapper: DEBUG
    com.site: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 

admin:
  path: HSuu22299dhs